### ISSUE TITLE
Allow input via URL

### ISSUE THREAD

**Issue by theosanderson** [fathominfo/delphy-web#23] opened 2024-11-08 15:47 UTC
Delphy seems really cool - congrats! Something that is probably on your roadmap anyway, but in case not, a feature request:

I would find it useful to be able to provide a URL for a CORS-accessible FASTA file and automatically spin up Delphy on the file. 

So e.g. https://delphy.fathom.info?fastaFile=http://mydomain.com/fasta.fa

**Comment by benfry** [comment] 2024-11-11 18:21
Thanks Theo, we had discussed it internally but hadn't prioritized it because of the trickiness with explaining to folks how to set up the correct CORS headers, etc. But useful for us to hear that this would actually be helpful and helps us bump it up the priority list.

We might also look into doing a simple pass-through proxy server implementation to handle the situations where people don't have control over the CORS settings, and just keep an eye on how well (or not) that holds up with usage.

**Comment by theosanderson** [comment] 2024-11-11 18:25
🙌  This sort of features come into their own as a means for the creators of other tools to send users to your tool with a specific dataset - I agree that for individual non-technical users it's likely confusing without the pass-through proxy

**Comment by benfry** [comment] 2024-11-11 18:27
Absolutely—and the success of a tool like this is really determined by how it wires in with everything else, so we're keenly aware of the importance of making this kind of thing work.

**Comment by corneliusroemer** [comment] 2024-11-25 12:33
The people behind the servers that you would get the fasta from have no issues with setting up CORS, I wouldn't worry about that 😀

Usher has been accepting Fasta like that from e.g. Covspectrum for long

Nextclade gets a bunch of stuff via URL and it's super helpful in a lot of cases for tech savvy users (and devs alike)

**Comment by theosanderson** [comment] 2024-12-05 16:48
Thank you for implementing this: if I understand correctly it can, as well as the UI, be used with `https://delphy.fathom.info/?https://mysite.com/myfasta.fa`. Predictably, my stretch goal for some point in the future would be to allow metadata input in a similar way, but this is fantastic in itself.

**Comment by benfry** [comment] 2024-12-06 15:21
Yes! Just checked with Mark and we confirmed that it's (already!) in and working. We're wrapping up testing and documentation of it before we announce it more broadly (i.e. the proxy explanation that comes up when you don't have CORS set properly needs to be simplified) but feel free to use it and see how it goes.

I'll close this issue since it's complete, so go ahead and open a new issue if you run into problems with the feature or would like additions to it (in fact, an issue to request the metadata feature would be helpful—totally agree that'd be useful too).

**Closed by benfry** 2024-12-06 15:21 UTC
